"""Derive a point cloud from the brochure's own heart artwork.

Hand-authoring a cardiac silhouette in bezier, blind, produces a blob. The
client's flyer already contains a correct heart, so we sample THAT: mask the
saturated red/blue anatomy off the bone background, then emit normalised
points for the canvas. Production replaces this with the MRI-derived mesh.

Also writes a debug PNG so the mask can be judged by eye, not by pixel counts.
"""

import json

from PIL import Image

SRC = "/Users/akash/CTX/Websites/IACTS 2026/assets/reference/brochure-p1.png"
OUT = "/Users/akash/CTX/Websites/IACTS 2026/mockups/heart-points.js"
DBG = "/tmp/heart_mask.png"

im = Image.open(SRC).convert("RGB")
W, H = im.size

# Tight on the heart body only: excludes the red callout icons on the left
# (x < 0.53W) and the CT/volume thumbnails on the right (x > 0.86W).
box = (int(W * 0.53), int(H * 0.12), int(W * 0.88), int(H * 0.605))
crop = im.crop(box)
cw, ch = crop.size

px = crop.load()
raw = []
# The flyer prints an ECG trace and a radiating fan just beneath the heart.
# The site renders its own trace, so clip everything below the cardiac apex.
apex_cut = int(ch * 0.755)
for y in range(0, min(ch, apex_cut), 1):
    for x in range(0, cw, 1):
        r, g, b = px[x, y]
        mx, mn = max(r, g, b), min(r, g, b)
        if mx - mn < 45 or mx < 60:
            continue
        is_red = r > g + 36 and r > b + 20
        is_blue = b > r + 18 and b > g + 8
        if not (is_red or is_blue):
            continue
        raw.append((x, y, 1 if is_blue else 0, r, g, b))

print("page", W, H, "crop", cw, ch, "masked", len(raw))


def pct(vals, q):
    s = sorted(vals)
    return s[min(len(s) - 1, max(0, int(len(s) * q)))]


xs = [p[0] for p in raw]
ys = [p[1] for p in raw]
# percentile bounds discard stray specks that would wreck normalisation
x0, x1 = pct(xs, 0.01), pct(xs, 0.99)
y0, y1 = pct(ys, 0.01), pct(ys, 0.99)
raw = [p for p in raw if x0 <= p[0] <= x1 and y0 <= p[1] <= y1]
bw, bh = max(1, x1 - x0), max(1, y1 - y0)
print("bbox", x0, y0, bw, bh, "kept", len(raw))

# uniform spatial thinning so density is even, not photo-weighted
GRID, TARGET = 2, 7500
buckets = {}
for x, y, blue, r, g, b in raw:
    buckets.setdefault(((x - x0) // GRID, (y - y0) // GRID), (x, y, blue, r, g, b))
sel = list(buckets.values())
step = max(1, len(sel) // TARGET)
sel = sel[::step][:TARGET]
print("emitted", len(sel))

# debug: paint the surviving points so the shape can be judged by eye
dbg = Image.new("RGB", (cw, ch), (247, 244, 239))
d = dbg.load()
for x, y, blue, r, g, b in sel:
    for dx in (0, 1):
        for dy in (0, 1):
            if x + dx < cw and y + dy < ch:
                d[x + dx, y + dy] = (40, 90, 180) if blue else (179, 18, 28)
dbg.save(DBG)
print("debug ->", DBG)

scale = 468.0 / max(bw, bh)
ox = 300 - (bw * scale) / 2
oy = 300 - (bh * scale) / 2

out = []
for x, y, blue, r, g, b in sel:
    out.append([
        round(ox + (x - x0) * scale, 1),
        round(oy + (y - y0) * scale, 1),
        blue,
        round((0.3 * r + 0.59 * g + 0.11 * b) / 255, 2),
    ])

with open(OUT, "w") as f:
    f.write("/* Point cloud sampled from the IACTS flyer's own heart artwork.\n")
    f.write("   [x, y, isVenous, luminance] in a 600x600 stage.\n")
    f.write("   Generated by tools/extract-heart.py - do not hand-edit. */\n")
    f.write("window.HEART_PTS=")
    f.write(json.dumps(out, separators=(",", ":")))
    f.write(";\n")
print("wrote", OUT)
